# Generated by Django 2.2.21 on 2021-06-09 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0003_auto_20210609_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_evenement',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 20, 15, 38, 840987), null=True),
        ),
    ]
