# Generated by Django 2.2.21 on 2021-06-09 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0004_auto_20210609_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_evenement',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 20, 24, 14, 235234), null=True),
        ),
    ]
