# Generated by Django 2.2.21 on 2021-06-10 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0005_auto_20210609_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(default='Super !'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_evenement',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 9, 21, 32, 393393), null=True),
        ),
    ]
