# Generated by Django 2.2.21 on 2021-06-10 12:45

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0006_auto_20210610_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='_post_likes_+', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_evenement',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 12, 45, 42, 333398), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='titre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
